version: "3.8"

services:
  web:
    container_name: next-antd
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8090:80"
    volumes:
      - /uploads/:/folder/in/container
      - uploads:/app/uploads